sudo: false

language: ruby
dist: bionic

git:
  depth: 1

install: true

notifications:
  disable: true

rvm:
  - 2.5
  - 2.6
  - 2.7

install:
  - bundle install

before_script:
  - ./bin/start-toxiproxy.sh

script:
  - bundle exec rake test
